---
- name: Create MySQL database
  community.mysql.mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present

- name: Create database user with name 'bob' and password '1234' with all database privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: '1234'
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
